### ISSUE TITLE
suggestion to align medium size indel

### ISSUE THREAD

**Issue by husamia** [ksahlin/StrobeAlign#1]
I have illumina paired reads 150bps that is targeted. The average coverage is pretty high. There is a known duplication of 77bps that is homozygous. It looks very good in IGV see snapshot.

With the default parameters the alignment looks like this. Is there way I can adjust the settings to get the alignment to properly anchor both ends of the reads.

![139854754-c310eb28-384f-4115-8a15-1d541ddb36f3](https://user-images.githubusercontent.com/13439952/141527637-94e14da7-85a0-46c6-8172-b0323cb0c1bd.png)

**Comment by ksahlin** [comment]
Hi @husamia,

Thanks for using strobealign. What do you mean by 'properly anchor' in this scenario?

If your reads come from a region containing a 77bp duplication relative to the reference, the reads spanning either duplication copy will have either a different 5' end or a different 3' end to the reference. This is exactly what I see in the figure and how I would want the alignments to look.

The misplaced (colorful) 5' region from read 2 in the read pair is a segment from the first duplication copy, and the misplaced (colorful) 3' region from read 2 is a segment from the second duplication copy 2. Notice that the reads have either the 5' end or the 3'end not fitting, never both ends. There is no good way to align two 77bp duplications within a read down to one segment in the reference. 

How do you envision the reads to be aligned? 

Best,
Kristoffer

**Comment by husamia** [comment]
Sorry I wasn't clear. In it's current form the caller completely misses it. I want it to insert the 77bps duplication from the 150bps reads so that the caller will recognize it's a duplication or an insertion technically. is that possible? also I wanted to ask. Does strobealign use all the sam flags?

**Comment by ksahlin** [comment]
I think the easiest way is to insert the 77bp sequence at the genomic position is to implement a small python script that reads in the file with the reference and output the modified sequence (perhaps this can be done with some unix tool too, or even manually if the target sequence is small).

As for using all flags, no it doesn't. Out of the 12 available 0/1 positions (https://broadinstitute.github.io/picard/explain-flags.html), strobealign writes bits to positions 1, 2, 5, 6, 7, 8. It also signals if both reads within a pair are unmapped (positions 3, 4). 

However, it currently does not signal in PE mode if a read is mapped, but its mate is unaligned, meaning that position 3 is one and position 4 is zero. This leaves out some flag combinations. There is actually no such state in strobealign in PE mode. Strobealign picks the best-paired score (can be separate genomic locations) or otherwise forces that alignment of the mate. I could look into the implementation to change this to allow for one of the mates being unmapped.

Also, it does not write secondary alignments (position 9) although this should be easy to add in the implementation by printing some additional alignment locations that it tried. 

Finally, it does not write to positions 10-12 which may relate to steps outside the alignment process (10,11) or out of score for short reads (12).

**Comment by ksahlin** [comment]
I may have answered a bit around your first question. As for "insert the 77bps duplication so that the caller will recognize it's a duplication or an insertion technically." I think the current alignment (as seen in your image) gives about as clear signal as can possibly be for the duplication. I would say the issue is with the SV caller in question not calling the region as a duplication.

**Comment by husamia** [comment]
GATK haplotype caller missed it completely. I tested several CNV callers and most of them missed it. I agree with "out of scope for short reads" would you say if my reads were 257bps would the aligner align it any different. by the way it's a known mutation.


This variant is known to ClinVar (August-2021): RCV000318696.6 (Pathogenic** - not provided), RCV000588290.1 (Pathogenic* - Junctional epidermolysis bullosa gravis of Herlitz). 
This variant is known to gnomAD (2.1) <Exomes+Genomes>: ALL:0.0042% - AFR:0.040% - AMR:0.0056%
HGVS Nomenclature (v15.11)

 
cDNA Level:
NM_000228.2:c.958_1034dup
gDNA Level:
Chr1(GRCh37):g.209803180_209803256dup
Protein Level:
p.(Asn345Lysfs*77)

**Comment by ksahlin** [comment]
Strange..

If your reads were significantly longer than 154bp (2*77) then they could anchor the duplication at both flanks. With significantly longer I would think at least 25-30nt more to anchor, so around 190bp and above. The duplications would then show as an insertion. A read that would span the duplication would have cigar `100M77I30M` if it was mapped 100bp before and 30bp after the duplication.

Do your callers also miss the region if you align with BWA and/or minimap2?

Perhaps the duplication is so small that it is not classified as a duplication in SV terminology, but goes under the category insertion? Then many CNV callers could fail. I had a look at this [benchmark paper](https://academic.oup.com/bib/article/22/3/bbaa056/5831479). Maybe [Lumpy](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2014-15-6-r84) or  [manta](https://academic.oup.com/bioinformatics/article/32/8/1220/1743909) works?

**Comment by husamia** [comment]
I think the callers will not make the call because the alignment is not what it should be. Namely, the sequence should be inserted. I tried bwa and minimap2 results are very similar. I have an issue with minimap2 to see what settings could be used to help. I suspect there might be something that could be adjusted.

**Comment by husamia** [comment]
Manta and Lumpy didn't call it.

**Comment by ksahlin** [comment]
Interesting that so many of the traditional SV callers and alignment combinations will miss it! I'm fairly confident that the alignment is as good as it gets for the reads though. And I see that minimap2 [agrees](https://github.com/lh3/minimap2/issues/826).

What is more surprising it that the SV callers miss it. I will try to reach out to some experts/developers.

**Comment by ksahlin** [comment]
I got a suggestion to try [Varlociraptor](https://github.com/varlociraptor/varlociraptor) for calling. Would you have time to try it out? My bet is still that the SV callers should be able to detect the signature that we can see by eye in the figure.

**Comment by husamia** [comment]
I will try it. I think I know why the SV callers miss it but I can't explain it at moment. I think required reassembly of reads which most callers don't do well.

**Comment by husamia** [comment]
I am not sure how to call variants with Varlociraptor. It asks for tumor sample.

**Comment by ksahlin** [comment]
I think that you are right in your guess. One would need a caller that can do a local assembly of the reads in the region.

**Comment by husamia** [comment]
@ksahlin I worked with minimap2 and I got some progress on that https://github.com/lh3/minimap2/issues/826
