### ISSUE TITLE
Installation issues on linux

### ISSUE THREAD

**Issue by ksahlin** [ksahlin/StrobeAlign#124]
For my promised benchmark on rackham on the master version.

INSTALLATION (on login node)

```
module load cmake
module load gcc

$ g++ --version
g++ (GCC) 12.2.0
$ cmake --version
cmake version 3.22.2

$ cmake -B build
$ cd build
$ make -j8
$ mv strobealign ~/bin/strobealign-master-38675ca
```

(btw, the `-B` option does not change dir for me so i manually had to `cd build`)

From the login node, running this works:

```
$ strobealign-master-38675ca 
  strobealign reference [reads1] [reads2] {OPTIONS}

    StrobeAlign 0.7.1
   ....
```

When submitting jobs with snakemake to nodes that runs strobealign, I get this issue:

```
strobealign-master-38675ca: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by strobealign-master-38675ca)
strobealign-master-38675ca: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by strobealign-master-38675ca)
strobealign-master-38675ca: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by strobealign-master-38675ca)
strobealign-master-38675ca: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by strobealign-master-38675ca)
strobealign-master-38675ca: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by strobealign-master-38675ca)
strobealign-master-38675ca: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by strobealign-master-38675ca)
```

Does this have to do with static vs dynamic builds? Release v0.7.1 did not have this issue.

**Comment by marcelm** [comment]
The message means that the binary was compiled against a more recent version of glibc/libstdc++ than available.

When you load the `gcc` module, recent versions of these libraries are made available and the compiled binary is linked against them. You need to ensure that the `gcc` module is also loaded when you run the Snakemake job. Loading the module sets some environment variables (in particular `LD_LIBRARY_PATH`) that point to the correct library versions.

When I compile StrobeAlign on the login node and submit a job using `sbatch`, the binary runs successfully because `sbatch` passes on the environment variables. Either `snakemake` does not pass on the environment variables or it does, but you ran it within a shell where you did not run `module load gcc`. If you did use `module load gcc` before running snakemake, you could try adding `envmodules: "gcc"` to the rule in the Snakefile, see https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#using-environment-modules.

**Comment by marcelm** [comment]
I assume that you got this working; is that correct?

**Comment by ksahlin** [comment]
Ah sorry, yes I did. Closing with this comment.
