### ISSUE TITLE
The separate indexing and alignment interface. 

### ISSUE THREAD

**Issue by ksahlin** [ksahlin/strobealign#133]
Related to  #59 but wasen't sure if I should post it there or create separate issue, went with the latter.

I was just attempting to benchmark commit ddf90e5 but ran into a snag. 

First, it took me a while to figure out that `--use-index` takes the `ref.fasta` and infers if a `ref.fasta.sti` is present and use it. It complains if `--use-index ref.fasta.sti` is provided with  the error message `strobealign: FASTA file must begin with '>' character, not 'S'`. I guess the confusion came from the documentation
```
reference     A pregenerated strobemers index file (.sti) or a reference in FASTA
                    format
```

Second, and more pressing, one advantage with the old interface of naming the index file manually is if we have indexes for different read lengths we name and use them as `-i ref.fa.100.sti` `--use-index ref.fa.100.sti` and so on (which is e.g. how my previous benchmarks were set up for the old interface). The limitation with the current is that we could have at most one index present with the current interface. 

Third, a small issue is that the current version creates an index without complaining if `-i ref.fa` is specified without `-r` or read files. This generates a default 150bp index but it is not ideal. 

The more pressing of these three items is number 2, as I would prefer not to redesign the benchmark rules again. I think it is kind of neat to have the indexing and alignment in separate rules for easy measure of peak memory etc. Should we either:

1. Name the indexes by appending the inferred read length like  `-r 100 -i ref.fa` would automatically yield an index file `ref.fa.100.sti`. A slight problem with this is when read length is inferred from reads. It would then be better to append the read length in some of the boundary conditions of the if statements controlling the ranges and check if they are equal for the provided reads and pre-generated index.
2. Or revert/revise to previous interface where `-i` requires a manually specified `.sti` file name

**Comment by marcelm** [comment]
The first problem (documentation) is on my to-do list (I have a separate list with small things that I didn’t want to post as issues here). I have submitted PR #134 as temporary workaround for the second issue. This is mentioned in #109, but we should possibly split it out. The third issue (index can be created without `-r`) is tracked in #109.

**Comment by marcelm** [comment]
> 1. Name the indexes by appending the inferred read length like  `-r 100 -i ref.fa` would automatically yield an index file `ref.fa.100.sti`. A slight problem with this is when read length is inferred from reads. It would then be better to append the read length in some of the boundary conditions of the if statements controlling the ranges and check if they are equal for the provided reads and pre-generated index.

Hi, I’m working on this at the moment. I’m not sure I understand the last sentence, but I think what you mean and what I thought in any case was that strobealign would only create one of six different indexes depending on read length. So for example, for any read length between 76 to 125, the output would always be `ref.fa.100.sti`.

100 represents the middle of that range and I call it "canonical read length" in the code.

I noticed that at the moment, the indexing parameters differ because the `max_dist` indexing parameter is directly derived from the read length (as `read_length - 70`). So one index created with `-r 101` would not be usable with `-r 100`.

I don’t think indices created with different max_dist settings are really compatible, or are they? If not, we would need to change this so that max_dist is computed not from the actual read length, but from the canonical one. So for read lengths 76 to 125, it would always be 100-70=80 (or perhaps a bit higher?). What’s your opinion?

**Comment by ksahlin** [comment]
> I’m not sure I understand the last sentence

Not sure what my sentence was supposed to say. But I have the same conclusion as you. We would name the index to whichever of the six(?) classes of seed parameters the read dataset was assigned to.

 > I noticed that at the moment, the indexing parameters differ because the max_dist indexing parameter is directly derived from the read length (as read_length - 70). So one index created with -r 101 would not be usable with -r 100.

Oh good catch.. It depends on how often the set of downstream syncmers (to link) span over `max_dist`. I don't remember how often that occurred, but I don't think it was too often. If a syncmer occur every 5th base on avg and the sampling window of the second syncmer is [6,12] syncmers downstream, they would (on average) be on positions [30,60] downstream. Some outliers may cause `max_dist`to be hit. 

As you say, with different `max_dist`,  the extracted seeds may differ in some regions when: (i) max_dist is active due to set of downstream syncmers too sparse ,and (ii) the linking also chooses the end syncmer to link with which with different max_dix may be different.

This gets worse the further away the read lengths are in the same class. For example, `-r 76` may hit max_dist much more often than  `-r 125`, hence more different seeds, compared to `-r 100` vs  `-r 101` which I guess would be near identical.

> I don’t think indices created with different max_dist settings are really compatible, or are they?

So per above, you are right. They are not. 

> If not, we would need to change this so that max_dist is computed not from the actual read length, but from the canonical one. So for read lengths 76 to 125, it would always be 100-70=80 (or perhaps a bit higher?). What’s your opinion?

This is tricky. A change to this will definitely cause a change in the results, for the better or worse. I did not benchmark this much, so there could be room for improvement with a bit of testing. Of course, the way it is currently set is more dynamic, so I guess setting a good canonical `max_dist` it is about minimising losses for some read lengths.

I think 125 and 150 are pretty common read lengths(?), if so could be worth setting parameters favourable to those lengths. Unfortunately I don't have a good guess. Would require some testing.

As a general point (which I think you are also making here with your comment) is that strobealign should complain if any parameters affecting the seeding are different between index and what the user wants, including `max_seed_len`.

**Comment by marcelm** [comment]
Thanks, this makes sense.

I’m happy the fruit fly dataset we’re using for testing has a slightly odd read length of 151 bp, otherwise I may not have noticed that this problem exists ...

On the 100'000 fruit fly reads, the alignment results change a tiny bit when we force the read length to `-r 150` instead of letting it use 151:
```
      18059 reads were unmapped before and after
*         3 reads became mapped
*         2 reads became unmapped
     172539 reads were mapped to same locus before and after
*      6620 reads were multimapper before and after, same alignment score (AS)
*        25 reads were multimapper before and after, better alignment score (AS)
*        27 reads were multimapper before and after, worse alignment score (AS)
*      2725 reads changed in another way
     200000 total reads
```
As discussed previously, the large number of "reads changed in another way" is (I’m sure) just due to a different sort order.

To get an idea of the effect on accuracy, I did something similar for the CHM13 150 bp dataset by running strobealign on it with different settings for the read length and got these numbers:

* `-r 126`: 94.1444
* `-r 150`: 94.1317
* `-r 175`: 94.14615

Admittedly, this is the "wrong direction", that is, we check "reads have 150 bp but we use a max_dist appropriate for a different read length". What we should check is "reads have different read length but max_dist would be appropriate for 150 bp". But I think it still conveys that the effect should be minor.

**Comment by marcelm** [comment]
> What stands out is `2725 reads changed in another way`. I would hope that only (or near only) multimapping reads would change, but this column refers to reads that are not multimappers and still change something, right? Do you know what is going on with those reads?

This number is similar to what the comparison script reports for the switch to pdqsort and also #191.

It looks a bit alarming because I ran the script on a dataset for which I don’t have the truth (I need to change that). So these "other changes" can be both "became incorrect" and "became correct" (and also "was not a multimapper, but should be one" or similar).  Here is how the report looks for CHM13 (2x150) when I use it to compare `-r 150` ("before") with `-r 126` ("after") and also provide the truth:
```
       2250 reads were unmapped before and after
*         8 reads became mapped
*         5 reads became unmapped
    1921514 reads were mapped to same locus before and after
*     65906 reads were multimapper before and after, same alignment score (AS)
*      1022 reads were multimapper before and after, better alignment score (AS)
*       922 reads were multimapper before and after, worse alignment score (AS)
       6935 reads were incorrect before and after (relative to truth)
*       733 reads became correct (relative to truth)
*       705 reads became incorrect (relative to truth)
    2000000 total reads
```

> Regarding accuracy: As long as the changes are in the order of 1 in 10,000 it's ok for me. I am assuming runtime could change also. Two notes on your check:
> 
>     * I suspect differences will be larger for shorter reads, eg the range 75-125.

I can check that range as well.
 
>     * Also, I am always concerned about how this translates to repetitive genomes such as maize or rye. Although you did benchmark on CHM13 which should be complex enough.

I will run a test on rye.

> > Admittedly, this is the "wrong direction", that is, we check "reads have 150 bp but we use a max_dist appropriate for a different read length". What we should check is "reads have different read length but max_dist would be appropriate for 150 bp". But I think it still conveys that the effect should be minor.
> 
> Didn't get what you meant by this but maybe because I am switching between too many tasks today :)

Rephrased: The index is going to be created with, for example, r=150. We should test what happens when the actual read length is 175 (or 126). But I did something else: I created the index with r=126 and then tested what happens when the actual read length is 150. (Because it was easier that way.)

**Comment by ksahlin** [comment]
> It looks a bit alarming because I ran the script on a dataset for which I don’t have the truth (I need to change that). So these "other changes" can be both "became incorrect" and "became correct" (and also "was not a multimapper, but should be one" or similar). Here is how the report looks for CHM13 (2x150) when I use it to compare -r 150 ("before") with -r 126 ("after") and also provide the truth:

I see, and from the numbers you reported it did not look like big changes (given 2M reads).

> The index is going to be created with, for example, r=150. We should test what happens when the actual read length is 175 (or 126). But I did something else: I created the index with r=126 and then tested what happens when the actual read length is 150. (Because it was easier that way.)

Right, that makes perfect sense and I agree.
