### ISSUE TITLE
Command-line options `-l` and `-u` do not work

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#199]
The intention for these options was apparently that they could be used to override `w_min` and `w_max`, but they are just ignored: `w_min` and `w_max` are always determined based on the choice of predefined setting (which in turn is based on read length). This was already the case in v0.7.1.

**Comment by ksahlin** [comment]
I see. I think I introduced them for setting lower and upper offsets from some "base value". When looking in the paper I found this: 

_We let 𝑤_𝑚𝑖𝑛=𝑘/(𝑘−𝑠+1)+𝑙 and 𝑤_𝑚ax=𝑘/(𝑘−𝑠+1)+𝑢 where l and u are integers that specify lower and upper offset._ 

Here `𝑘/(𝑘−𝑠+1)` should be considered the base value as it is the thinning factor. It could be good to fix l and u so that they work as they are useful for grid searches of parameter settings. That could be investigated in a small student project with experimental emphasis.
