### ISSUE TITLE
avx512 support

### ISSUE THREAD

**Issue by jianshu93** [ksahlin/StrobeAlign#6]
Hello Kristoffer,

g++ -std=c++14 main.cpp source/index.cpp source/xxhash.c source/ksw2_extz2_sse.c source/ssw_cpp.cpp source/ssw.c -lz -fopenmp -o StrobeAlign -O3 -march=skylake-avx512

This works for my avx512 supported server (gcc v8.3.0). I think this is even faster. Could be added to the readme for users who have those machines.

Jianshu

**Comment by ksahlin** [comment]
Wow great! Will do.

Also, I'm currently in a development period and I have already done some additional improvements in accuracy and runtime over the version published yesterday. I hope to push them in a couple of days, currently fixing some bugs caused by the integration of ssw.

**Comment by ksahlin** [comment]
I just released v0.2 and now mention this in the README. I also tried to compile with `-march=skylake-avx512` but my machine does not support it so I can't verify the increase in speed.

As for the new version, I observe improvements both in accuracy and speed on my datasets for v0.2 over v0.1 (aligning to hg38). 

The accuracy should be universally higher on all datasets. As for speed, your dataset is of different nature to hg38, so it's difficult to predict if you will see further speed improvement or reduction (I'm now using ssw instead of ksw on some instances). It depends on how often your alignments go into rescue mode.
